<?php

/**
 * @file
 * Checks user name availability on registration page.
 */

function username_check_form_user_register_form_alter(&$form) {
  $module_path = drupal_get_path('module', 'username_check');
  $config = \Drupal::config('username_check.settings');
  $mode     = $config->get('username_check_mode');
  $mailmode = $config->get('username_check_mail_mode', 'auto');
  $delay = $config->get('username_check_delay');
  if($mode != 'off') {
    global $base_url;
    $form['#attached']['css'] = array($module_path.'/username_check.css');
    $form['#attached']['js'] = array($module_path.'/username_check.js');
    $form['#attached']['js'][] = array(
    'data' => array('usernameCheck' => array(
      'ajaxUrl' =>  'http://localhost/d8/username_check/isunique',
      'delay' => $delay,
    )),
    'type' => 'setting',
    );
    $form['account']['name']['#field_suffix'] = '<span id="username-check-informer">&nbsp;</span>';
    $form['account']['name']['#suffix'] = '<div id="username-check-message"></div>';
  }
  if($mailmode != 'off') {
   $form['#attached']['css'] = array($module_path.'/username_check.css');
    $form['#attached']['js'][] = $module_path.'/username_check_mail.js';
    $form['#attached']['js'][] = array(
    'data' => array('usermailCheck' => array(
      'ajaxUrl' =>  $base_url.'/username_check/isuniquemail',
      'delay' => $delay,
    )),
    'type' => 'setting',
    );
    //print_r($form);die();
    $form['account']['mail']['#field_suffix'] = '<span id="mail-check-informer">&nbsp;</span>';
    $form['account']['mail']['#suffix'] = '<div id="mail-check-message"></div>';
  }

}

function username_check_form_user_form_alter(&$form) {
  global $base_url;
  $module_path = drupal_get_path('module', 'username_check');
  $config = \Drupal::config('username_check.settings');
  $mode = $config->get('username_check_mode');
  $delay = $config->get('username_check_delay');
  if($mode != 'off'){
    $form['#attached']['css'] = array($module_path.'/username_check.css');
    $form['#attached']['js'] = array($module_path.'/username_check.js');
    $form['#attached']['js'][] = array(
    'data2' => array('usernameCheck' => array(
      'ajaxUrl' =>  $base_url.'/username_check/isuniqueprofile',
      'delay' => $delay,
    )),
    'type' => 'setting',
  );
    $form['account']['name']['#field_suffix'] = '<span id="profile-check-informer">&nbsp;</span>';
    $form['account']['name']['#suffix'] = '<div id="profile-check-message"></div>';
  }
}

function _username_check_mail_load_resources($mode) {
  $module_path = drupal_get_path('module', 'username_check');
  drupal_add_css($module_path . '/username_check.css');
  drupal_add_js($module_path . '/username_check_mail.js');

  drupal_add_js(array(
    'mailCheck' => array(
      'ajaxUrl' => url('username_check/isuniquemail', array('absolute' => TRUE)),
      'delay'   => variable_get('username_check_delay', 1),
    ),
  ), 'setting');

}
